from fastapi import APIRouter

from ..config import DATA_DISCLAIMER

router = APIRouter(prefix="/api/theory", tags=["theory"])

ENTRIES = [
    {
        "id": "factor-investing",
        "title": "Factor Investing",
        "simple": "Instead of picking stories, you group stocks by shared characteristics — cheapness, momentum, profitability — and ask whether those characteristics have historically been paid.",
        "technical": "A factor is a systematic source of return (and risk) that shows up in the cross-section after controlling for the market. In practice we build long-short or long-only sleeves ranked on a characteristic.",
        "formula": "r_i = α_i + β_i MKT + v_i VAL + m_i MOM + q_i QUAL + ε_i",
        "variables": "r_i stock return; β market beta; v,m,q factor loadings; ε residual.",
        "intuition": "If cheap stocks keep beating expensive stocks after you account for the market, there is either a risk premium or a persistent behavioural mistake. The lab does not pick a side — it shows the path.",
        "use": "Tilting a long-only book toward Value or Quality, or running a dedicated factor sleeve against a benchmark.",
        "limits": "Premia crowd, fade, and change with the regime. A 20-year table is not a 20-year promise.",
        "example": "A 15-stock quality sleeve vs Nifty over 2020–22: quality lagged in the 2020 bounce and held up in 2022. That is the conversation, not a single Sharpe.",
    },
    {
        "id": "capm",
        "title": "CAPM",
        "simple": "In the textbook, the only risk you get paid for is market risk. Everything else should average to zero.",
        "technical": "E[R_i] = R_f + β_i (E[R_m] − R_f). Beta is Cov(R_i, R_m)/Var(R_m).",
        "formula": "α = R_p − [R_f + β(R_m − R_f)]",
        "variables": "R_p portfolio return, R_f risk-free, R_m market, β slope vs the market.",
        "intuition": "If two stocks have the same beta, CAPM says they should have the same expected return. Factor research exists because that often fails in the data.",
        "use": "Cost of equity in a DCF; a first-pass benchmark for a long-only fund.",
        "limits": "Single factor, sensitive to the market proxy, assumes you can borrow at R_f.",
        "example": "A low-vol utility with β=0.6 should earn less than the market. Empirically, low-vol has often earned *more* per unit of risk — the anomaly the Low-Vol sleeve is probing.",
    },
    {
        "id": "emh",
        "title": "Efficient Market Hypothesis",
        "simple": "Prices already reflect available information, so beating the market after costs should be hard.",
        "technical": "Weak/semi-strong/strong forms depending on the information set. Factor premia can still exist as compensation for risk even in an efficient market.",
        "formula": "E[R_{t+1} | Φ_t] = required return(risk)",
        "variables": "Φ_t is the information set at t.",
        "intuition": "Efficiency is a useful null, not a religion. The lab treats every pretty backtest as guilty until transaction costs, bias and regime are discussed.",
        "use": "A reminder to ask 'who is on the other side of this trade?'",
        "limits": "Limits to arbitrage, slow diffusion of information, and institutional constraints all punch holes in the strong version.",
        "example": "Momentum surviving for decades is either a risk story or a slow behavioural loop. EMH does not tell you which.",
    },
    {
        "id": "alpha",
        "title": "Alpha",
        "simple": "Return left over after you have paid for the risks you knowingly took.",
        "technical": "Jensen's alpha vs CAPM, or intercept in a multi-factor regression (Fama–French, Carhart, q-factor).",
        "formula": "α_p = R_p − [R_f + β(R_m − R_f)]",
        "variables": "Same as CAPM. In a 6-factor lab model, subtract the other factor premia too.",
        "intuition": "High return is not alpha. A leveraged small-cap book *should* beat cash. Alpha is the leftover.",
        "use": "Manager evaluation; residual in a factor attribution.",
        "limits": "Alpha is model-relative. Change the factors, change the leftover. Also in-sample alpha decays.",
        "example": "A momentum sleeve with +4% vs the S&P and β=1.1 has less alpha than the headline spread suggests.",
    },
    {
        "id": "beta",
        "title": "Beta",
        "simple": "How hard the book moves when the market moves.",
        "technical": "Slope coefficient in an OLS of excess asset returns on excess market returns.",
        "formula": "β = Cov(R_p, R_m) / Var(R_m)",
        "variables": "Usually estimated on 2–5 years of daily or weekly returns.",
        "intuition": "Beta 1.3 is a volume knob, not a skill score.",
        "use": "Hedging, risk budgeting, CAPM expected return.",
        "limits": "Unstable through crises; thin-trading biases; depends on the index you pick (S&P vs Nifty).",
        "example": "NVDA's beta vs NASDAQ is a different animal from vs Nifty. Always name the market.",
    },
    {
        "id": "risk-premium",
        "title": "Risk Premium",
        "simple": "The extra expected return for holding something that hurts in bad times.",
        "technical": "E[R] − R_f. Equity risk premium is the market's; factor premia are additional prices of risk.",
        "formula": "ERP ≈ E[R_m] − R_f",
        "variables": "Can be estimated historically or implied from discounted cash flows.",
        "intuition": "If a strategy only pays off in good times, it should not command a premium. If it pays when you *need* cash, maybe it should.",
        "use": "Setting expected returns in a DCF or in a strategic asset allocation.",
        "limits": "Historical averages are noisy. 1926–2024 is one sample path.",
        "example": "Value's premium is often justified as distress risk. Whether that is enough after costs is an empirical question.",
    },
    {
        "id": "value-premium",
        "title": "Value Premium",
        "simple": "Cheaper stocks have, on average, beaten expensive ones. The argument is whether that is risk or a behavioural discount.",
        "technical": "HML in Fama–French: high book-to-market minus low. We also use earnings yield, EV/EBITDA, PE.",
        "formula": "Value score ∝ rank(EY) + rank(1/PE) + rank(1/PB) + rank(1/EV EBITDA)",
        "variables": "EY = earnings/price. Ranks are cross-sectional, 0–100 in this lab.",
        "intuition": "Paying 8x earnings vs 35x is a different claim on the same rupee of profit. Sometimes the 8x name is cheap because it is dying.",
        "use": "Long-only tilts; classic quant value books.",
        "limits": "Value traps, accounting distortion, and long droughts (2017–20 was a character-building window).",
        "example": "Energy majors in 2022 looked cheap and then delivered. Cheap software in 2021 often wasn't a bargain, it was a slowing growth story.",
    },
    {
        "id": "momentum",
        "title": "Momentum Effect",
        "simple": "Winners over the last 6–12 months have tended to keep winning — until they don't.",
        "technical": "12-1 month residual return is the academic default. We blend 12m and 6m total return ranks.",
        "formula": "MOM_i = 0.7 R_{t-12,t} + 0.3 R_{t-6,t}",
        "variables": "Skipping the most recent month is common to avoid short-term reversal. This lab uses a simpler blend.",
        "intuition": "Underreaction, fund flows, and crowded stops all produce the same chart. The crash in Mar 2020 is the page you should not skip.",
        "use": "Trend overlay; ranking inside a sector.",
        "limits": "High turnover, high crash risk, capacity. Transaction costs eat a lot of the paper premium.",
        "example": "If India VIX spikes and the momentum sleeve is packed with the same five names, assume the next week can gap through your stops.",
    },
    {
        "id": "quality",
        "title": "Quality Factor",
        "simple": "Profitable, conservative-balance-sheet firms have often earned more than the junkie names, without taking obvious extra market risk.",
        "technical": "ROE, ROA, accruals, leverage, earnings stability. Novy-Marx (gross profitability) is the academic cousin.",
        "formula": "Quality ∝ rank(ROE) + rank(ROA) − rank(D/E)",
        "variables": "ROE = NI/Equity; D/E = total debt/equity.",
        "intuition": "A 25% ROE compounder should not trade like a 6% ROE cyclicals name. Sometimes the market forgets; sometimes the 25% is peak-cycle.",
        "use": "Core long-only quality; defensive overlay in high-vol regimes.",
        "limits": "Quality gets expensive. Paying 40x for 'quality' is just growth with better branding.",
        "example": "Staples and HUL-type names screen well. That does not mean they are a buy at any multiple.",
    },
    {
        "id": "size",
        "title": "Size Effect",
        "simple": "Smaller firms have historically earned a bit more than large ones — with more pain, less liquidity, and a premium that has been thinner since the 1980s.",
        "technical": "SMB in Fama–French. We rank on −log(market cap) so small names score high.",
        "formula": "Size score = percentile(−ln(MCap))",
        "variables": "MCap in the same currency. Mixing US and India without a local-cap adjustment is a student-lab shortcut — flagged as such.",
        "intuition": "Small names are harder to hold in a drawdown. If you get paid, that is partly the point.",
        "use": "Satellite small-cap sleeve, not a core 60% allocation for a student book.",
        "limits": "Survivorship, delisting bias, and transaction costs. Academic SMB looks better than a live India SME book.",
        "example": "Our NSE names pick up a size tilt vs AAPL/MSFT by construction. Don't confuse that with a pure India small-cap premium.",
    },
    {
        "id": "volatility",
        "title": "Volatility & Low-Vol Anomaly",
        "simple": "Lower-volatility stocks have often produced better Sharpe ratios than high-vol names. CAPM says that should not happen.",
        "technical": "Realised σ, sometimes idiosyncratic vol after a market regression. Betting-against-beta (Frazzini–Pedersen) is the leveraged cousin.",
        "formula": "LowVol score = percentile(−σ_{252})",
        "variables": "σ annualised from daily returns.",
        "intuition": "Leverage-constrained investors buy high-beta names for lottery payoff. That can leave low-beta names under-owned.",
        "use": "Defensive overlay; minimum-variance sleeves.",
        "limits": "Crowding into the same utilities/staples; rate-sensitive; can lag for years in a melt-up.",
        "example": "KO, PG, Power Grid will hog a low-vol sleeve. In a 2023-style megacap melt-up they look sleepy, not wrong.",
    },
    {
        "id": "diversification",
        "title": "Diversification",
        "simple": "Don't put the whole book in one story. Correlation — not the number of tickers — is what actually diversifies.",
        "technical": "Portfolio variance = w' Σ w. Effective N ≈ 1/HHI.",
        "formula": "HHI = Σ w_i²    diversification score = 1 − HHI",
        "variables": "w_i are weights that sum to 1.",
        "intuition": "20 semiconductor names is one bet. 8 names across banks, staples, energy and IT is closer to a book.",
        "use": "Position limits, sector caps in the builder.",
        "limits": "Correlations jump to 1 in a crash. Diversification is a fair-weather friend unless you have tested the 2020 window.",
        "example": "HHI of 0.08 (roughly 12–15 names, not concentrated) is a reasonable student-book target.",
    },
    {
        "id": "portfolio-construction",
        "title": "Portfolio Construction",
        "simple": "How you weight names often matters as much as which names you picked.",
        "technical": "Equal weight, cap weight, factor weight, risk parity, optimiser with constraints.",
        "formula": "w_i^{eq} = 1/N     w_i^{cap} = MCap_i / Σ MCap     w_i^{fac} ∝ score_i",
        "variables": "Constraints: sector cap, max name weight, turnover budget.",
        "intuition": "Cap weight is a momentum-of-size bet. Equal weight is a small-cap tilt. Neither is 'neutral'.",
        "use": "The builder lets you drag weights and watch Sharpe/drawdown move. That is the lesson.",
        "limits": "Optimisers overfit. We keep rules simple on purpose.",
        "example": "Capping any sector at 25% stops a quality book from becoming 'IT + staples' by accident.",
    },
    {
        "id": "risk-adjusted",
        "title": "Risk-Adjusted Returns",
        "simple": "Return per unit of pain. A 30% year with a 40% drawdown is a different product from 14% with an 8% drawdown.",
        "technical": "Sharpe, Sortino, Treynor, Information Ratio, Calmar.",
        "formula": "Sharpe = (R_p − R_f)/σ_p    Sortino uses downside σ    IR = (R_p − R_b)/TE",
        "variables": "R_f 4.2% in this lab as a sample-period stand-in, not a forecast.",
        "intuition": "Sharpe punishes upside vol too. Sortino is kinder to books that gap up. IR asks whether you beat *your* benchmark, not cash.",
        "use": "Comparing two sleeves with different vol.",
        "limits": "All of these assume the past σ is the right denominator. It isn't in a regime shift.",
        "example": "A low-vol sleeve can win on Sharpe and lose on total return in a bull market. Report both.",
    },
    {
        "id": "benchmarking",
        "title": "Benchmarking",
        "simple": "Pick a fair yardstick or you will congratulate yourself for taking market risk.",
        "technical": "S&P 500 for US large cap, Nifty 50 for India large cap. Factor books should also show equal-weight and cap-weight variants.",
        "formula": "Active return = R_p − R_b",
        "variables": "Tracking error is the σ of that difference.",
        "intuition": "Beating Nifty with a 40% US tech book is not skill, it is a different mandate.",
        "use": "Every backtest in this lab plots strategy vs benchmark vs equal-weight vs cap-weight.",
        "limits": "Wrong benchmark is a silent lie. State it.",
        "example": "NASDAQ as a benchmark for a value sleeve will make value look worse than it is. Use S&P or a value index.",
    },
    {
        "id": "active-passive",
        "title": "Active vs Passive Investing",
        "simple": "Passive owns the market cheaply. Active tries to deviate and get paid after fees.",
        "technical": "Active share, fees, and the arithmetic of active management (Sharpe 1991): the average active dollar underperforms passive by the fee.",
        "formula": "Active share = ½ Σ |w_i − w_i^{bench}|",
        "variables": "High active share is necessary but not sufficient for outperformance.",
        "intuition": "A factor book is active even if the rule is mechanical. You are still off-benchmark.",
        "use": "Decide whether the factor tilt is worth the tracking error.",
        "limits": "Passive is not risk-free. Cap-weight passive is a momentum/size bet of its own.",
        "example": "An equal-weight Nifty sleeve is 'passive-ish' but is actually a mid-cap tilt vs the official index.",
    },
]


@router.get("")
def theory():
    return {"disclaimer": DATA_DISCLAIMER, "entries": ENTRIES}


@router.get("/{eid}")
def one(eid: str):
    hit = next((e for e in ENTRIES if e["id"] == eid), None)
    if not hit:
        from fastapi import HTTPException
        raise HTTPException(404)
    return hit
