export const METRICS: Record<string, { title: string; simple: string; technical: string; formula: string; vars: string; intuition: string; use: string; limits: string; example: string; why: string }> = {
  pe: {
    title: "Price / Earnings",
    simple: "How many years of current earnings the market is paying for.",
    technical: "Price per share divided by trailing twelve-month EPS.",
    formula: "PE = Price / EPS",
    vars: "EPS is net income over diluted shares, usually TTM.",
    intuition: "A PE of 12 vs 28 is a different claim on the same rupee of profit. Cheap can be a trap.",
    use: "First-pass value screen, compared inside a sector — never across banks vs software blindly.",
    limits: "Negative earnings break it. Cyclicals look cheap at the peak.",
    example: "A bank at 11x with ROE 14% is a different animal from a paint company at 11x.",
    why: "Valuation is the price of the factor bet, not the bet itself.",
  },
  pb: {
    title: "Price / Book",
    simple: "What you pay for a rupee of accounting equity.",
    technical: "Market cap / book value of equity.",
    formula: "PB = Market Cap / Book Equity",
    vars: "Book is accounting equity, not replacement value.",
    intuition: "Useful for banks and cyclicals. Almost silent for asset-light software.",
    use: "Value sleeve construction, especially financials.",
    limits: "Intangibles and buybacks distort book.",
    example: "SBI at ~1.4x book vs HDFC at a premium is a quality-vs-price conversation.",
    why: "Classic HML uses book-to-market. We keep PB visible so the academic link is not a black box.",
  },
  roe: {
    title: "Return on Equity",
    simple: "Profit earned on shareholders' capital.",
    technical: "Net income / average book equity.",
    formula: "ROE = Net Income / Equity",
    vars: "Leverage inflates ROE — always pair with D/E.",
    intuition: "A 22% ROE compounder can stay expensive for a long time. That is not the same as cheap quality.",
    use: "Quality score. Cross-check with ROA so leverage doesn't fake it.",
    limits: "Buybacks and thin equity bases juice ROE.",
    example: "FMCG names in India often print high ROE with modest leverage — that is actual quality.",
    why: "Profitability is the least glamorous predictor and one of the more stubborn ones.",
  },
  roa: {
    title: "Return on Assets",
    simple: "Profit per rupee of assets — harder to fake with leverage than ROE.",
    technical: "Net income / total assets.",
    formula: "ROA = Net Income / Assets",
    vars: "Banks will look structurally lower. Compare inside the sector.",
    intuition: "If ROE is high and ROA is not, the story is leverage.",
    use: "Quality screen alongside ROE.",
    limits: "Asset-light vs asset-heavy industries are not comparable.",
    example: "Visa's ROA vs a steel mill is a category error. Rank inside the peer set.",
    why: "Keeps the quality factor from becoming a leveraged-equity factor.",
  },
  momentum: {
    title: "Momentum",
    simple: "Stocks with strong recent relative performance receive higher momentum scores.",
    technical: "Blend of 12-month and 6-month total return, ranked 0–100 in the universe.",
    formula: "MOM = 0.7 R_12m + 0.3 R_6m",
    vars: "R is total return over the lookback, sample-universe percentile.",
    intuition: "A high score is exposure to the characteristic, not a promise. Momentum can reverse sharply when the regime breaks.",
    use: "Trend overlay; ranking inside a sector rather than across oil vs software.",
    limits: "Crashes in liquidity shocks (see Feb–Mar 2020 in the seed). Turnover is real.",
    example: "NVDA-type names will hog the sleeve after a run. That is the feature and the risk.",
    why: "High score means stronger exposure to momentum — check the regime map before treating it as a free lunch.",
  },
  value: {
    title: "Value",
    simple: "Cheaper names versus the rest of this book on PE, PB and earnings yield.",
    technical: "Composite of inverted PE/PB/EV EBITDA and earnings yield, cross-sectional rank.",
    formula: "VAL ∝ rank(EY) + rank(1/PE) + rank(1/PB)",
    vars: "All ranks are within the 75-name sample, not the whole CRSP tape.",
    intuition: "Cheap is a starting point. Distressed cheap and compounding cheap are different species.",
    use: "Tilt against a growth-heavy benchmark.",
    limits: "Value traps, accounting noise, long droughts.",
    example: "Energy in 2022 was cheap and then paid. Cheap software in 2021 often wasn't.",
    why: "The value premium is a risk or a behaviour story. The lab shows the path, it does not pick a church.",
  },
  quality: {
    title: "Quality",
    simple: "Profitability and a less-stretched balance sheet.",
    technical: "ROE + ROA − leverage, ranked.",
    formula: "QUAL ∝ rank(ROE) + rank(ROA) − rank(D/E)",
    vars: "D/E is total debt over equity.",
    intuition: "Quality is not a personality trait. Peak-cycle ROE looks like quality until the cycle turns.",
    use: "Defensive core; usually holds up better in high-vol windows.",
    limits: "Gets expensive. 40x 'quality' is just growth with nicer stationery.",
    example: "HUL and COST screen well. Price still matters.",
    why: "In the 2022 hiking cycle, quality and value were better company than momentum.",
  },
  growth: {
    title: "Growth",
    simple: "Revenue and EPS running faster than the rest of the sample.",
    technical: "Rank of revenue growth and EPS growth.",
    formula: "GR ∝ rank(ΔRev) + rank(ΔEPS)",
    vars: "Sample-period growth, not analyst FY3 estimates — a limitation.",
    intuition: "Growth is a characteristic. Paying 50x for it is a valuation decision.",
    use: "Identify duration. Pair with value so you don't own only the expensive stuff.",
    limits: "No forward estimates in this educational set. Past growth is sticky until it isn't.",
    example: "Lilly vs PFE is a growth-vs-reset pair inside the same sector.",
    why: "Duration hurts when the 10Y rips. Watch the pulse strip.",
  },
  size: {
    title: "Size",
    simple: "Smaller names score higher — that is the academic size-premium convention.",
    technical: "Percentile of −ln(market cap).",
    formula: "SIZE = percentile(−ln(MCap))",
    vars: "US and India caps sit in one book. That mixes two markets — flagged in the notes.",
    intuition: "Smaller is not better. It is a different risk. Liquidity vanishes first.",
    use: "Satellite tilt, not the whole student book.",
    limits: "Survivorship, delisting, costs. Academic SMB is kinder than a live SME book.",
    example: "AAPL will sit at the bottom of this score by construction.",
    why: "Cap-weighting a 'size' book defeats the point.",
  },
  low_vol: {
    title: "Low Volatility",
    simple: "Names that have moved around less over the last year.",
    technical: "Percentile of −annualised realised σ.",
    formula: "LV = percentile(−σ_252)",
    vars: "σ from daily returns, 252-day window.",
    intuition: "Defensive. Lags in melt-ups. The anomaly is that Sharpe is often better, not that total return is.",
    use: "When India VIX or the 2020-style window is the worry.",
    limits: "Crowds into staples/utilities. Rate sensitive.",
    example: "KO, PG, Power Grid will dominate. That is the sleeve, not a bug.",
    why: "CAPM says high vol should earn more. The data has often disagreed. That disagreement is the research question.",
  },
  alpha: {
    title: "Alpha",
    simple: "Performance beyond what the book's market exposure would lead you to expect.",
    technical: "Jensen's alpha: leftover after CAPM. In this lab the Alpha Score is a weighted factor rank, which is not the same thing.",
    formula: "α = R_p − [R_f + β(R_m − R_f)]",
    vars: "R_f is 4.2% in the sample as a stand-in, not a forecast.",
    intuition: "Do not confuse the 0–100 Alpha Score with Jensen alpha. One is a research ranking, the other is a realised leftover.",
    use: "Score → ranking. Regression alpha → 'did we actually get paid after beta?'",
    limits: "Model-relative. Change the factors, change the leftover.",
    example: "A 82 Alpha Score with β 1.3 vs Nifty may still have modest Jensen alpha.",
    why: "High alpha is attractive, but check whether it remains after market risk and factor exposure.",
  },
  sharpe: {
    title: "Sharpe Ratio",
    simple: "Excess return per unit of total volatility.",
    technical: "Annualised (R_p − R_f) / σ_p.",
    formula: "Sharpe = (R_p − R_f) / σ_p",
    vars: "σ is annualised stdev of returns. R_f = 4.2% here.",
    intuition: "Punishes upside vol too. A strategy that gaps up looks 'worse' on Sharpe than it feels.",
    use: "Comparing two sleeves with different vol.",
    limits: "Assumes σ is the right pain measure. It isn't in a crash.",
    example: "Low-vol can win Sharpe and lose total return in a bull year. Report both.",
    why: "Raw return without this is how people ship lottery tickets as 'alpha'.",
  },
  sortino: {
    title: "Sortino Ratio",
    simple: "Like Sharpe, but only penalises downside moves.",
    technical: "(R_p − R_f) / downside deviation.",
    formula: "Sortino = (R_p − R_f) / σ_down",
    vars: "σ_down uses returns below 0 (or below R_f, depending on house style).",
    intuition: "Kinder to books with upside gaps.",
    use: "When the return distribution is clearly skewed.",
    limits: "Still a sample statistic. Thin left tails look great until they don't.",
    example: "Momentum often has a better Sharpe than Sortino because the left tail is fat.",
    why: "If Sharpe and Sortino disagree, read the drawdown chart next.",
  },
  drawdown: {
    title: "Maximum Drawdown",
    simple: "The largest peak-to-trough decline in the selected window.",
    technical: "min(equity / running max − 1).",
    formula: "MDD = min_t (P_t / max_{s≤t} P_s − 1)",
    vars: "P is the marked equity curve.",
    intuition: "This is what a student book actually feels like. CAGR doesn't.",
    use: "Position sizing. If MDD is −32%, a 2x levered version is not a cute idea.",
    limits: "Depends on the window. Miss 2020 and you will lie to yourself.",
    example: "Mar 2020 is in the sample on purpose.",
    why: "A 14% CAGR with a 38% hole is a different product from 11% with a 12% hole.",
  },
  beta: {
    title: "Beta",
    simple: "How hard the book moves when the chosen market moves.",
    technical: "OLS slope of portfolio returns on benchmark returns.",
    formula: "β = Cov(R_p, R_m) / Var(R_m)",
    vars: "Name the market. S&P and Nifty are not interchangeable.",
    intuition: "A volume knob, not a skill score.",
    use: "Hedging, CAPM expected return.",
    limits: "Unstable in crises.",
    example: "A 1.25 beta value book 'outperforming' in a bull is mostly the volume knob.",
    why: "Alpha without beta is incomplete. Always read them together.",
  },
  var: {
    title: "Value at Risk (95%)",
    simple: "A daily loss that was worse than this only 5% of the time in the sample.",
    technical: "5th percentile of the daily return distribution.",
    formula: "VaR_95 = quantile_{0.05}(R)",
    vars: "Historical, not parametric. No fancy covariance engine.",
    intuition: "A weather report for the left tail, not an insurance policy.",
    use: "Risk dashboard. Pair with CVaR, which asks 'and then how bad?'",
    limits: "2020-03-16 is one observation. History under-samples wars and pandemics.",
    example: "If VaR is −2.1% and CVaR is −3.8%, the tail is fat — don't size as if it were Gaussian.",
    why: "Students over-trust a single vol number. VaR/CVaR force a look at the tail.",
  },
  cvar: {
    title: "CVaR (Expected Shortfall)",
    simple: "Average loss on days that are already worse than VaR.",
    technical: "E[R | R ≤ VaR_95].",
    formula: "CVaR = mean of the worst 5% days",
    vars: "Same sample as VaR.",
    intuition: "VaR is a threshold. CVaR is the hole below it.",
    use: "When you care about crash days, not average days.",
    limits: "Still only as good as the window.",
    example: "Momentum's CVaR gap vs quality in Mar 2020 is the teaching moment.",
    why: "Two books with the same vol can have very different CVaR. That's the point of this page.",
  },
  ir: {
    title: "Information Ratio",
    simple: "Active return per unit of tracking error versus the benchmark you actually chose.",
    technical: "(R_p − R_b) / tracking error.",
    formula: "IR = (R_p − R_b) / TE",
    vars: "TE = σ(R_p − R_b).",
    intuition: "Did you beat *this* yardstick, not cash?",
    use: "Active mandate evaluation.",
    limits: "Wrong benchmark makes a pretty IR into a lie.",
    example: "Value vs NASDAQ will look worse than value vs S&P. State the benchmark.",
    why: "A student report that only shows CAGR vs cash is incomplete.",
  },
};

export const FACTOR_PROSE = {
  value: "Cheap versus expensive in this universe. Composite of PE, PB, EV/EBITDA and earnings yield.",
  momentum: "Recent relative performance. High scores mean the name has been winning — and is crowded.",
  quality: "Profitability and leverage. The boring sleeve that often behaves in high-vol windows.",
  size: "Smaller cap → higher score. Academic convention, not a recommendation to go micro-cap.",
  growth: "Revenue and EPS growth versus peers. Duration. Hurts when discount rates jump.",
  low_vol: "Low realised volatility. Defensive. Lags in melt-ups. The Sharpe is the interesting bit.",
};
